# @package hydra.job_logging
# python logging configuration for tasks
version: 1
formatters:
  simple:
    format: '%(message)s'
  detailed:
    format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: detailed
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    formatter: detailed
    filename: trainer.log
root:
  level: INFO
  handlers: [console, file]

disable_existing_loggers: False